name: Frontend deployment
on:
  push:
    branches: [main]
    paths:
      - "**"
concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
jobs:
  check-syntax:
      runs-on: ubuntu-latest
      steps:
         - name: checkout code
           uses: actions/checkout@v4
         - name: setup node
           uses: actions/setup-node@v4
           with:
             node-version: '22'
             cache: 'npm'
             cache-dependency-path: package-lock.json      
         - name: install dependencies
           run: npm install 
         - name: Run ESLint 
           run: npm run lint -- --deny-warnings
         - name: set the formet
           run: npx prettier --write  "src/**/*.(ts|jsx)" 
         - name: Check Prettier formatting
           run: npx prettier --check  "src/**/*.(ts|jsx)"
         - name: TypeScript strict type check
           run: npx tsc --noEmit
  Test:
      needs: check-syntax
      runs-on: ubuntu-latest
      steps:
        - name: checkout the code
          uses: actions/checkout@v4
        - name: setup node 
          uses: actions/setup-node@v4
          with:
            node-version: '22'
            cache: 'npm'
            cache-dependency-path: package-lock.json 
        - name: install depenedencies
          run: npm install
        - name: test every component
          run: npm test -- --coverage --reporter=verbose || echo "No Test define"
        - name: save the covergae into the artifect
          if: always()
          uses: actions/upload-artifact@v7
          with:
           name: forntend-coverage-${{github.run_number}}
           path: coverage/
           retention-days: 14
  Build:
     needs: Test
     runs-on: ubuntu-latest
     steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node 
        uses: actions/setup-node@v4
        with:
         node-version: '22'
         cache: 'npm'
         cache-dependency-path: package-lock.json
      - name: install dependencies
        run: npm install ci
      - name: build the app
        run: npm run build
      - name: upload build to artifect
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: frontend-build-${{github.sha}}
          path: dist/
          retention-days: 14   
  Deploy:
     needs: Build
     runs-on: ubuntu-latest
     steps:
        - name: checkout the code
          uses: actions/checkout@v4
        - name: downlaod artifect
          uses: actions/download-artifact@v8
          with:
            name: frontend-build-${{github.sha}}
        - name: setup aws
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.REGION}}
        - name: setup terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform-version: "1.14.6"
        - name: terraform init
          working-directory: ./terraform
          run: terraform init 
        - name: terraform apply
          working-directory: ./terraform
          run: terraform apply --auto-approve
        - name: zip the bundle 
          run: | 
             zip -r app-${{github.sha}} . -x "terraform/*" ".git/*" 
        - name: copy the archive to s3
          run: aws s3 cp -r app-${{github.sha}} s3://danish-frontend-app-bucket
        - name: deploy the code to code deploy
          run: aws deploy create-deployment \
            --application-name my-frontend-app \
            --deployment-group-name my-frontend-app-deployment-group \
            --s3-location bucket=danish-frontend-app-bucket,key=app-${{ github.sha }}.zip,bundleType=zip 
