name: Frontend deployment
on:
  push:
    branches: [main]
    paths:
      - "**"
jobs:
  check-syntax:
      runs-on: ubuntu-latest
      steps:
         - name: checkout code
           uses: actions/checkout@v4
         - name: setup node
           uses: actions/setup-node@v4
           with:
             node-version: '22'
             cache: 'npm'
             cache-dependency-path: package-lock.json      
         - name: install oxlint
           run: npm install oxlint       
         - name: Run ESLint 
           run: npm run lint -- --deny-warnings
         
         - name: Check Prettier formatting
           run: npm install prettier && npx prettier --check  "src/**/*.(ts|jsx)"
         - name: TypeScript strict type check
           run: npx tsc --noEmit
      
